### ISSUE TITLE
Windows compilation

### ISSUE THREAD

**Issue by andreasrosdal** [wunderfox/wunderfox#4]
Run gcc --version
  gcc --version
  CC=gcc CXX=g++ ./configure --host=x86_64-pc-mingw3[2](https://github.com/wunderfox/wunderfox/actions/runs/11223653611/job/31198728849#step:6:2)
  shell: C:\Program Files\Git\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
gcc.exe (x86_64-posix-seh-rev2, Built by MinGW-W64 project) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

creating cache ./config.cache
checking host system type... x86_64-pc-mingw[3](https://github.com/wunderfox/wunderfox/actions/runs/11223653611/job/31198728849#step:6:3)2
checking target system type... x86_64-pc-mingw32
checking build system type... x86_6[4](https://github.com/wunderfox/wunderfox/actions/runs/11223653611/job/31198728849#step:6:4)-pc-mingw32
checking for gawk... gawk
checking for perl5... no
checking for perl... /usr/bin/perl
checking for gcc... gcc
checking whether the C compiler (gcc  ) works... yes
checking whether the C compiler (gcc  ) is a cross-compiler... no
checking whether we are using GNU C... yes
checking whether gcc accepts -g... yes
checking for c++... g++
checking whether the C++ compiler (g++  ) works... yes
checking whether the C++ compiler (g++  ) is a cross-compiler... no
checking whether we are using GNU C++... yes
checking whether g++ accepts -g... yes
checking for ranlib... ranlib
checking for ml[6](https://github.com/wunderfox/wunderfox/actions/runs/11223653611/job/31198728849#step:6:7)4... no
checking for as... /c/mingw64/bin/as
checking for ar... ar
checking for ld... link
checking for strip... strip
checking for windres... windres
checking for w32api version >= 3.14... yes
checking for windres version >= 2.14.90... (GNU
./configure: line 383[7](https://github.com/wunderfox/wunderfox/actions/runs/11223653611/job/31198728849#step:6:8): test: (GNU: integer expression expected
./configure: line 3868: C:/Program: No such file or directory
checking for Windows SDK being recent enough... no
configure: error: You are targeting Windows version 0x060[10](https://github.com/wunderfox/wunderfox/actions/runs/11223653611/job/31198728849#step:6:11)000, but your SDK only supports up to version 0x06010000. Install and use an updated SDK, or target a lower version using --with-windows-version. Alternatively, try running the Windows SDK Configuration Tool and selecting a newer SDK. See https://developer.mozilla.org/En/Windows_SDK_versions for more details on fixing this.
Error: Process completed with exit code 1.

https://github.com/wunderfox/wunderfox/actions/runs/11223653611/job/31198728849

**Comment by K4sum1** [comment]
You'll probably want to build on Windows, inside a VM probably. FWDK might be too new, but the easiest to set up to build.

https://archive.org/details/funny-windows-development-kit

This Mozconfig might be a useful reference when setting the browser up to build.

https://github.com/Eclipse-Community/UXP/blob/custom-fixed/mozconfigs/hydra-win
